-- Drop tables if they exist (optional for dev only)
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE services CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE users CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      NULL;
END;
/

-- Create USERS table
CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR2(50),
    last_name VARCHAR2(50),
    email VARCHAR2(100),
    password VARCHAR2(100),
    phone_number VARCHAR2(20),
    address VARCHAR2(200),
    role VARCHAR2(20),
    is_active CHAR(1),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create SERVICES table
CREATE TABLE services (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100),
    description VARCHAR2(255),
    price NUMBER(10,2),
    duration_minutes NUMBER,
    category VARCHAR2(50),
    is_active CHAR(1),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE pets (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(50) NOT NULL,
    species VARCHAR2(50) NOT NULL,
    breed VARCHAR2(50),
    age NUMBER,
    gender VARCHAR2(20),
    date_of_birth DATE,
    description CLOB,
    medical_notes CLOB,
    emergency_contact VARCHAR2(100),
    is_active CHAR(1) DEFAULT 'Y',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    owner_id NUMBER NOT NULL,
    CONSTRAINT fk_pet_owner FOREIGN KEY (owner_id) REFERENCES users(id)
);


-- Insert sample data
INSERT INTO services (name, description, price, duration_minutes, category, is_active)
VALUES
('Basic Grooming', 'Complete wash, dry, and brush for your pet', 45.00, 60, 'GROOMING', 'Y');

INSERT INTO users (first_name, last_name, email, password, phone_number, address, role, is_active)
VALUES
('Admin', 'User', 'admin@pawpal.com', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', '555-0001', '123 Admin St', 'ADMIN', 'Y');
